#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FABRIC="$ROOT/fabric/company/v1/fabric"

fail() {
  echo "$1" >&2
  exit 1
}

run() {
  echo "+ $*"
  "$@"
}

run_expect_fail() {
  echo "+ $* (expecting failure)"
  set +e
  local output
  output="$($@ 2>&1)"
  local status=$?
  set -e
  echo "$output"
  if [[ $status -eq 0 ]]; then
    fail "Expected command to fail, but it succeeded: $*"
  fi
}

seed_customer_input() {
  local dir="$1"
  mkdir -p "$dir/docs/customer-input"
  cat > "$dir/docs/customer-input/customer-input.md" <<'INPUT'
# Customer Input

Problem statement:
Care operations, compliance, and engineering teams cannot consistently see shared risk posture across environments. Existing status updates are fragmented and create delays, duplicated work, and audit gaps.

Intended outcome:
Create a single workflow that captures risks, owners, mitigation status, and review cadence so teams can make faster decisions and demonstrate traceable progress.

Target users:
- Security operations manager
- Compliance lead
- Engineering manager

MVP scope:
- Register assets and risks with clear owner assignment
- Track mitigation tasks with due dates and current status
- Provide milestone-aligned reporting with explicit acceptance criteria
- Support periodic review checkpoints and unresolved-risk visibility

Constraints and non-negotiables:
- Must align with existing release process and environment model
- Must preserve audit-ready change history
- Must avoid introducing net-new external tooling in MVP
- Must provide role-based access boundaries for sensitive data
INPUT
}

# Test 1 + Test 2 share setup
TEST_DIR_A="$(mktemp -d "${TMPDIR:-/tmp}/fabric-pm-semantics-a.XXXXXX")"
seed_customer_input "$TEST_DIR_A"
run "$FABRIC" pm:intake --target "$TEST_DIR_A"
run "$FABRIC" pm:brief-readiness --target "$TEST_DIR_A"

if [[ -f "$TEST_DIR_A/docs/product/project-brief.md" ]]; then
  fail "Test 1 failed: project brief should not exist after pm:brief-readiness"
fi

echo "Test 1 passed: no brief generated by pm:brief-readiness"

run "$FABRIC" pm:brief-draft --target "$TEST_DIR_A"
if [[ ! -f "$TEST_DIR_A/docs/product/project-brief.md" ]]; then
  fail "Test 2 failed: project brief should exist after pm:brief-draft"
fi
if [[ ! -f "$TEST_DIR_A/docs/pm/brief/brief-draft.stamp.json" ]]; then
  fail "Test 2 failed: brief draft marker should exist at docs/pm/brief/brief-draft.stamp.json"
fi
if [[ -f "$TEST_DIR_A/docs/pm/intake/brief-draft.stamp.json" ]]; then
  fail "Test 2 failed: legacy marker path docs/pm/intake/brief-draft.stamp.json should not be written"
fi

echo "Test 2 passed: brief generated by pm:brief-draft"

# Test 3
TEST_DIR_B="$(mktemp -d "${TMPDIR:-/tmp}/fabric-pm-semantics-b.XXXXXX")"
run_expect_fail "$FABRIC" pm:brief-approve --target "$TEST_DIR_B"
echo "Test 3 passed: pm:brief-approve fails without draft"

# Test 4
TEST_DIR_C="$(mktemp -d "${TMPDIR:-/tmp}/fabric-pm-semantics-c.XXXXXX")"
run_expect_fail "$FABRIC" pm:derive-values --target "$TEST_DIR_C"
echo "Test 4 passed: pm:derive-values fails without approved brief"

echo "pm semantics smoke: OK"
