-- German translations for the 20 vaccination catalog items introduced by the BAG
-- Impfplan reconciliation. Unlike the EviPrev German pass, this is not a back-
-- translation of the English base columns -- both the English content and this German
-- content trace back independently to the same source, "Schweizerischer Impfplan 2026"
-- (BAG/EKIF, Stand Februar 2026), which is itself entirely in German. The English
-- columns on preventive_catalog_items remain the required base/default-locale content
-- (DEFAULT_CATALOG_LOCALE = 'en' in supabasePreventiveCatalog.js, matching the existing
-- EviPrev precedent); this table is what lets German-locale users see the app in the
-- source document's own language instead of falling back to the English paraphrase.

insert into public.preventive_catalog_item_translations (item_id, locale, name, cadence_label, why_it_matters, recommendation_text) values
  ('tdap-booster', 'de', 'Diphtherie-, Tetanus- und Keuchhusten-Impfung', 'Grundimmunisierung im Säuglingsalter, danach Auffrischimpfungen bis ins Erwachsenenalter', 'Schützt vor Diphtherie, Tetanus und Keuchhusten und kann bei einer Impfung während der Schwangerschaft auch Neugeborene schützen.', 'Schliesse die Grundimmunisierung im Säuglingsalter ab, danach Auffrischimpfungen mit 4–7, 11–15, 25, 45 und 65 Jahren sowie danach alle 10 Jahre.'),
  ('polio-vaccine', 'de', 'Polio-Impfung (IPV)', 'Grundimmunisierung im Säuglingsalter, danach Auffrischimpfungen bis 15 Jahre', 'Schützt vor Poliomyelitis, einer Krankheit, die in einigen Teilen der Welt noch verbreitet ist.', 'Schliesse die IPV-Grundimmunisierung im Säuglingsalter ab, inklusive der Auffrischimpfungen mit 4–7 und 11–15 Jahren.'),
  ('hepatitis-b-vaccine', 'de', 'Hepatitis-B-Impfung', 'Grundimmunisierung im Säuglingsalter oder risikobasierte Erwachsenenserie', 'Schützt vor einer Hepatitis-B-Infektion und den damit verbundenen langfristigen Leberschäden.', 'Schliesse die Grundimmunisierung im Säuglingsalter ab, oder eine 3-Dosen-Serie im Erwachsenenalter, wenn Risiko, Exposition oder Beruf dies nahelegen.'),
  ('hib-vaccine', 'de', 'Haemophilus-influenzae-Typ-b-Impfung (Hib)', 'Grundimmunisierung im Säuglingsalter', 'Schützt Säuglinge vor schweren Hib-Infektionen wie Hirnhautentzündung.', 'Schliesse die 3-Dosen-Hib-Serie im Säuglingsalter ab.'),
  ('rotavirus-vaccine', 'de', 'Rotaviren-Impfung', '2-Dosen-Schluckimpfung im Säuglingsalter', 'Senkt das Risiko einer schweren Rotavirus-Gastroenteritis bei Säuglingen.', 'Verabreiche die 2-Dosen-Schluckimpfung gegen Rotaviren im Alter von 2 und 4 Monaten.'),
  ('mmr-vaccine', 'de', 'MMR-Impfung (Masern, Mumps, Röteln)', 'Grundimmunisierung im Säuglingsalter, Nachholimpfung bei Geburt nach 1963', 'Schützt vor Masern-, Mumps- und Röteln-Ausbrüchen.', 'Schliesse die 2-Dosen-Grundimmunisierung im Säuglingsalter ab; bist du nach 1963 geboren und ohne dokumentierte Immunität, hole die Impfung im Erwachsenenalter nach.'),
  ('varicella-vaccine', 'de', 'Varizellen-Impfung (Windpocken)', 'Grundimmunisierung im Säuglingsalter; Nachholimpfung vor dem 40. Lebensjahr, falls nicht immun', 'Senkt das Risiko von Windpocken und deren Komplikationen.', 'Schliesse die 2-Dosen-Grundimmunisierung im Säuglingsalter ab, oder hole die Impfung vor dem 40. Lebensjahr nach, wenn du nicht immun bist.'),
  ('hpv-vaccine', 'de', 'HPV-Impfung', '2- oder 3-Dosen-Serie, Alter 11–26 Jahre', 'Senkt das Risiko mehrerer HPV-assoziierter Krebsarten und von Genitalwarzen.', 'Schliesse die 2-Dosen-Serie im Alter von 11–14 Jahren ab, oder eine 3-Dosen-Serie bei späterem Beginn, bis zum Alter von 26 Jahren.'),
  ('meningococcal-b-vaccine', 'de', 'Meningokokken-B-Impfung', 'Serie im Säuglings-/Jugendalter oder risikobasiert', 'Schützt vor invasiven Erkrankungen durch Meningokokken der Serogruppe B, der häufigsten Ursache invasiver Meningokokken-Erkrankungen bei Kleinkindern.', 'Schliesse die 4CMenB-Serie im Säuglings- oder Jugendalter ab, oder eine risikobasierte Serie, falls indiziert.'),
  ('meningococcal-acwy-vaccine', 'de', 'Meningokokken-ACWY-Impfung', 'Dosis im Jugendalter oder risikobasiert', 'Schützt vor invasiven Erkrankungen durch Meningokokken der Serogruppen A, C, W und Y.', 'Lass dich im Jugendalter mit einer Dosis MCV-ACWY impfen, oder erhalte eine risikobasierte Serie, falls indiziert.'),
  ('shingles-vaccine', 'de', 'Gürtelrose-Impfung (Herpes Zoster)', '2-Dosen-Serie ab 50 oder 65 Jahren', 'Senkt das Risiko einer Gürtelrose und lang anhaltender Nervenschmerzen.', 'Schliesse die 2-Dosen-Serie mit Shingrix® ab 65 Jahren ab, oder bereits ab 50 bzw. 18 Jahren bei erhöhtem Immunrisiko.'),
  ('pneumococcal-vaccine', 'de', 'Pneumokokken-Impfung', 'Grundimmunisierung im Säuglingsalter, oder ab 65 Jahren bzw. risikobasiert', 'Hilft, schwere Lungenentzündungen und Blutbahninfektionen zu verhindern.', 'Schliesse die Grundimmunisierung im Säuglingsalter ab, oder erhalte eine Erwachsenendosis ab 65 Jahren, oder früher bei einer entsprechenden chronischen Grunderkrankung.'),
  ('influenza-vaccine', 'de', 'Grippeimpfung', 'Jährlich ab 65 Jahren, oder in jedem Alter risikobasiert', 'Senkt das Risiko schwerer Komplikationen bei saisonaler Grippe.', 'Lass dich ab 65 Jahren jährlich gegen Grippe impfen (Hochdosis-Impfstoff ab 75 Jahren), oder in jedem Alter, wenn du schwanger bist, im Gesundheitswesen arbeitest oder eine entsprechende chronische Grunderkrankung hast.'),
  ('covid-19-booster', 'de', 'COVID-19-Auffrischimpfung', 'Jährlich, risikobasiert', 'Senkt das Risiko eines schweren COVID-19-Verlaufs in Risikogruppen.', 'Lass dich jährlich gegen COVID-19 auffrischen, wenn du eine entsprechende chronische Grunderkrankung hast, schwanger bist oder Trisomie 21 hast.'),
  ('rsv-vaccine', 'de', 'RSV-Impfung (Erwachsene)', 'Einmalige Dosis, 60–74 Jahre risikobasiert oder ab 75 Jahren', 'Kann bei älteren Erwachsenen das Risiko einer schweren unteren Atemwegsinfektion durch RSV senken.', 'Lass dich ab 75 Jahren einmalig gegen RSV impfen, oder bereits ab 60 Jahren bei einer entsprechenden chronischen Grunderkrankung.'),
  ('rsv-infant-immunization', 'de', 'RSV-Immunisierung für Neugeborene und Säuglinge', 'Mütterliche Impfung oder Antikörperdosis beim Säugling', 'Schützt Neugeborene und Säuglinge in ihrer ersten RSV-Saison vor schweren Erkrankungen und Hospitalisationen.', 'Lass dich bei einem Geburtstermin zwischen Oktober und März gegen Ende der Schwangerschaft gegen RSV impfen, oder dein Säugling erhält eine einmalige Dosis eines langwirksamen monoklonalen Antikörpers, falls keine mütterliche Impfung erfolgt ist.'),
  ('hepatitis-a-vaccine', 'de', 'Hepatitis-A-Impfung', 'Risikobasierte 2-Dosen-Serie', 'Hilft, eine akute Hepatitis-A-Leberinfektion zu verhindern, besonders in Risikosituationen.', 'Schliesse die 2-Dosen-Serie ab, wenn Reisen, chronische Lebererkrankung, Beruf oder andere Risikofaktoren dies nahelegen.'),
  ('fsme-vaccine', 'de', 'FSME-Impfung (Frühsommer-Meningoenzephalitis)', '3-Dosen-Serie, danach Auffrischung alle 10 Jahre', 'Schützt vor Frühsommer-Meningoenzephalitis, die in weiten Teilen der Schweiz verbreitet ist.', 'Schliesse die 3-Dosen-Serie ab, wenn du in einem Risikogebiet wohnst oder dich dort aufhältst, und frische die Impfung danach alle 10 Jahre auf.'),
  ('rabies-vaccine', 'de', 'Tollwut-Impfung (präexpositionell)', 'Risikobasierte 2-Dosen-Serie', 'Senkt das Tollwutrisiko bei regelmässigem Kontakt zu Tieren oder Fledermäusen.', 'Schliesse eine präexpositionelle 2-Dosen-Serie ab, wenn dein Beruf oder Hobby regelmässigen Kontakt zu Tieren, Fledermäusen oder Tollwutproben mit sich bringt.'),
  ('tuberculosis-bcg-vaccine', 'de', 'Tuberkulose-Impfung (BCG)', 'Einmalige Dosis im Säuglingsalter, risikobasiert', 'Senkt das Risiko einer disseminierten Tuberkulose bei Säuglingen mit erhöhtem Expositionsrisiko.', 'Verabreiche eine einmalige BCG-Dosis im ersten Lebensjahr, wenn dein Säugling ein erhöhtes Tuberkulose-Expositionsrisiko hat.')
on conflict (item_id, locale) do update set
  name = excluded.name,
  cadence_label = excluded.cadence_label,
  why_it_matters = excluded.why_it_matters,
  recommendation_text = excluded.recommendation_text,
  updated_at = now();
