-- German translations for the full current EviPrev-reconciled catalog (40
-- items): cadence_label, why_it_matters, and recommendation_text, preserving
-- each item's clinical meaning (cadence bands, risk-gating language,
-- shared-decision-making phrasing) rather than a loose paraphrase. Band-level
-- cadence overrides remain English-only (a known, documented gap from the
-- i18n foundation work) — this only translates the item-level base fields
-- that preventive_catalog_item_translations covers.

insert into public.preventive_catalog_item_translations (item_id, locale, cadence_label, why_it_matters, recommendation_text) values
  ('annual-wellness-visit', 'de', 'Jährlich', 'Regelmäßige Vorsorgeuntersuchungen helfen, Veränderungen frühzeitig zu erkennen und deinen Vorsorgeplan aktuell zu halten.', 'Vereinbare einen jährlichen Vorsorgetermin, um deinen Vorsorgeplan gemeinsam mit deiner Ärztin oder deinem Arzt zu überprüfen und anzupassen.'),
  ('blood-pressure-check', 'de', 'Alle 3 Jahre, ab 40 jährlich', 'Blutdruckkontrollen können Risikofaktoren fürs Herz erkennen, bevor Symptome auftreten.', 'Lass deinen Blutdruck vor dem 40. Lebensjahr mindestens alle 3 Jahre kontrollieren, danach jährlich – oder öfter, wenn deine Ärztin bzw. dein Arzt engmaschigere Kontrollen empfiehlt.'),
  ('cholesterol-screening', 'de', 'Alle 2 bis 5 Jahre, je nach Herz-Kreislauf-Risiko', 'Diese Untersuchung hilft, das Herz-Kreislauf-Risiko im Blick zu behalten und rechtzeitig vorzubeugen.', 'Lass dein Herz-Kreislauf-Risiko und deine Cholesterinwerte ab 40 (Männer) bzw. 50 (Frauen) bestimmen, danach alle 2 bis 5 Jahre je nach Risikoscore.'),
  ('diabetes-screening', 'de', 'Alle 1 bis 3 Jahre, je nach Diabetesrisiko', 'Ein Screening kann Veränderungen des Blutzuckers frühzeitig erkennen und rechtzeitige Vorsorge ermöglichen.', 'Plane ein Diabetes-Screening ab 40 (Männer) bzw. 50 (Frauen), danach alle 1 bis 3 Jahre je nach Risikofaktoren.'),
  ('cervical-cancer-screening', 'de', 'Alle 3 Jahre', 'Regelmäßige Vorsorge kann Zellveränderungen frühzeitig erkennen und eine gezielte Nachsorge ermöglichen.', 'Folge dem empfohlenen Intervall für dein Alter: Zytologie alle 3 Jahre, ab 30 wahlweise Zytologie oder HPV-Test alle 3 Jahre.'),
  ('prostate-health-discussion', 'de', 'Alle 1 bis 3 Jahre (PSA), nach gemeinsamer Entscheidung', 'Ein rechtzeitiges Gespräch hilft dir, gemeinsam mit deiner Ärztin oder deinem Arzt den passenden Vorsorgeweg zu wählen.', 'Beginne mit etwa 50 Jahren ein Gespräch zur Prostatagesundheit, damit die Vorsorgeentscheidung zu deinen Werten und deinem persönlichen Risiko passt; die PSA-Testfrequenz richtet sich danach nach deinem Ergebnis.'),
  ('influenza-vaccine', 'de', 'Jährlich', 'Die jährliche Impfung senkt das Risiko eines schweren Verlaufs in der Grippesaison.', 'Lass dich jedes Jahr gegen Grippe impfen, idealerweise vor Beginn der jeweiligen Grippesaison.'),
  ('tdap-booster', 'de', 'Alle 10 Jahre', 'Auffrischimpfungen erhalten den Schutz vor schweren bakteriellen Infektionen.', 'Lass deine Tetanus-, Diphtherie- und Keuchhusten-Auffrischung alle 10 Jahre erneuern, um den Schutz aufrechtzuerhalten.'),
  ('shingles-vaccine', 'de', '2-Dosen-Serie ab 50 Jahren', 'Die Impfung senkt das Risiko einer Gürtelrose und lang anhaltender Nervenschmerzen.', 'Schließe die 2-Dosen-Impfserie gegen Gürtelrose ab 50 Jahren ab, im zeitlichen Abstand nach Empfehlung deiner Ärztin oder deines Arztes.'),
  ('covid-19-booster', 'de', 'Saisonale Auffrischempfehlung', 'Auffrischimpfungen senken das Risiko eines schweren Atemwegsverlaufs und einer Krankenhauseinweisung.', 'Folge der aktuellen Empfehlung deiner Ärztin oder deines Arztes zur Auffrischimpfung, um den Schutz vor schweren COVID-19-Verläufen zu erhalten.'),
  ('hepatitis-b-vaccine', 'de', 'Serie je nach Risiko und Vorgeschichte', 'Die Impfung schützt vor einer Hepatitis-B-Infektion und langfristigen Leberschäden.', 'Schließe die Hepatitis-B-Impfserie ab, wenn Alter, Vorgeschichte oder Risikoprofil dies nahelegen.'),
  ('colorectal-cancer-screening', 'de', 'Alle 2 Jahre (Stuhltest) oder alle 10 Jahre (Darmspiegelung)', 'Regelmäßige Darmkrebsvorsorge hilft, Vorstufen und Krebs früher zu erkennen.', 'Beginne ab 50 mit der Darmkrebsvorsorge – entweder alle 2 Jahre ein Stuhltest (FIT) oder alle 10 Jahre eine Darmspiegelung.'),
  ('breast-cancer-screening', 'de', 'Alle 2 Jahre (Mammographie)', 'Regelmäßige Mammographie kann das Risiko senken, an Brustkrebs zu versterben – durch frühere Erkennung, allerdings mit einer realen Chance auf Überdiagnose, die es mit deiner Ärztin oder deinem Arzt abzuwägen gilt.', 'Sprich mit deiner Ärztin oder deinem Arzt über Nutzen und Risiken der Mammographie und lasse dich danach alle 2 Jahre zwischen 50 und 75 untersuchen, wenn ihr euch gemeinsam dafür entscheidet.'),
  ('lung-cancer-screening', 'de', 'Alle 1 bis 2 Jahre (Low-Dose-CT)', 'Bei hohem Risiko kann ein Low-Dose-CT Lungenkrebs früher erkennen, birgt aber auch eine reale Chance auf ein falsch-positives Ergebnis.', 'Wenn du aktuell oder früher stark geraucht hast (etwa 15+ Packungsjahre, Rauchstopp innerhalb der letzten 10 Jahre), sprich mit deiner Ärztin oder deinem Arzt über ein jährliches Low-Dose-CT-Screening zwischen 50 und 75 Jahren.'),
  ('osteoporosis-screening', 'de', 'Individuell, je nach Frakturrisiko-Einschätzung', 'Eine Knochendichtemessung hilft, das Frakturrisiko frühzeitig zu erkennen und vorzubeugen – abgewogen gegen das Risiko einer Überversorgung bei niedrigem Risiko.', 'Lass zwischen 50 und 65 dein Frakturrisiko (FRAX) einschätzen; ab 65 erfolgt eine Knochendichtemessung individuell nach deinem persönlichen Risiko statt routinemäßig für alle.'),
  ('abdominal-aortic-aneurysm-screening', 'de', 'Einmalige Ultraschalluntersuchung', 'Eine einmalige Ultraschalluntersuchung kann ein Aneurysma bei geeigneten Personen vor einem Riss erkennen.', 'Wenn du aktuell oder früher geraucht hast, lass zwischen 65 und 75 Jahren einmalig eine Bauch-Ultraschalluntersuchung auf ein Aortenaneurysma durchführen.'),
  ('depression-screening', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Regelmäßiges Screening kann Depressionen früher erkennen, sodass die Behandlung rechtzeitig beginnen kann.', 'Ein kurzer Zwei-Fragen-Check ("Interessenverlust" / "Niedergeschlagenheit") bei Routineterminen kann eine Depression frühzeitig aufdecken, wenn die Behandlung meist am besten wirkt.'),
  ('anxiety-screening', 'de', 'Regelmäßiges Screening', 'Frühzeitiges Screening kann Angstsymptome sichtbar machen und dich mit evidenzbasierter Versorgung verbinden.', 'Ein kurzes Gespräch über Stimmung und Ängste bei Routineterminen kann Sorgen frühzeitig aufdecken; sprich anhaltende Sorgen oder Niedergeschlagenheit bei jedem Termin an.'),
  ('hiv-screening', 'de', 'Wiederholung je nach fortbestehendem Risiko', 'HIV-Screening unterstützt eine frühe Diagnose und Behandlung und verbessert so den Gesundheitsverlauf.', 'Wenn ein HIV-Risikofaktor bei dir vorliegt, lass dich testen und wiederhole den Test regelmäßig je nach fortbestehendem Risiko.'),
  ('hepatitis-c-screening', 'de', 'Einmalig, danach je nach Risikofaktoren', 'Ein einmaliges Hepatitis-C-Screening kann eine stille Infektion aufdecken und langfristige Leberschäden verhindern.', 'Lass einmalig einen Hepatitis-C-Test durchführen; wiederhole ihn bei fortbestehenden Risikofaktoren.'),
  ('tobacco-cessation-support', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Nachfragen zum Tabakkonsum und das Angebot von Unterstützung erhöhen die Chance auf einen erfolgreichen Rauchstopp.', 'Wenn du rauchst oder vapst, sprich mit deiner Ärztin oder deinem Arzt über Unterstützung beim Aufhören – Nikotinersatz und andere Behandlungen verbessern deine Erfolgschancen deutlich.'),
  ('alcohol-use-screening', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Ein Screening kann riskanten Alkoholkonsum frühzeitig erkennen und zu kurzer Beratung führen.', 'Ein kurzes Gespräch über Alkoholkonsum kann riskantes Trinkverhalten frühzeitig erkennen und dich bei Bedarf mit Unterstützung verbinden.'),
  ('pneumococcal-vaccine', 'de', 'Ab 50 oder risikobasiert, nach Schema', 'Die Pneumokokken-Impfung hilft, schwere Lungenentzündungen und Blutbahninfektionen zu verhindern.', 'Sprich die Pneumokokken-Impfung an, sobald du das empfohlene Alter oder Risikoprofil erreichst.'),
  ('rsv-vaccine', 'de', 'Einmalige Saisondosis nach Alter/Risiko', 'Die RSV-Impfung kann bei älteren Erwachsenen das Risiko schwerer unterer Atemwegsinfektionen senken.', 'Sprich mit deiner Ärztin oder deinem Arzt über eine einmalige RSV-Dosis pro Saison, abhängig von deinem Alter und Risiko.'),
  ('hpv-vaccine', 'de', '2- bis 3-Dosen-Serie je nach Alter/Vorgeschichte', 'Die HPV-Impfung senkt das Risiko mehrerer Krebsarten und von Genitalwarzen.', 'Schließe die HPV-Impfserie im empfohlenen Alter ab, um das langfristige Krebsrisiko zu senken.'),
  ('mmr-vaccine', 'de', 'Nachholimpfung bei fehlender Immunität', 'Die MMR-Impfung schützt vor Masern-, Mumps- und Röteln-Ausbrüchen.', 'Hole die MMR-Impfung nach, wenn dein Immunstatus unklar ist.'),
  ('varicella-vaccine', 'de', '2-Dosen-Serie bei fehlender Immunität', 'Die Windpocken-Impfung senkt das Risiko einer Erstinfektion und von Komplikationen.', 'Schließe die Windpocken-Impfserie ab, wenn du noch nicht immun bist.'),
  ('hepatitis-a-vaccine', 'de', '2-Dosen-Serie bei Indikation', 'Die Hepatitis-A-Impfung hilft, eine akute Leberinfektion zu verhindern – besonders in Risikosituationen.', 'Schließe die Hepatitis-A-Impfserie ab, wenn Reisen, Beruf oder andere Risikofaktoren dies nahelegen.'),
  ('meningococcal-vaccine', 'de', 'Nach Risikofaktoren und Exposition', 'Die risikobasierte Meningokokken-Impfung schützt vor einer schnell verlaufenden, schweren Meningokokken-Erkrankung.', 'Sprich die Meningokokken-Impfung mit deiner Ärztin oder deinem Arzt an, wenn deine Risikofaktoren oder Exposition dies nahelegen.'),
  ('polio-vaccine', 'de', 'Serie vervollständigen, falls unvollständig', 'Eine Polio-Nachholimpfung kann Erwachsene schützen, die in der Kindheit nicht vollständig geimpft wurden.', 'Vervollständige die Polio-Nachholserie, wenn deine Impfvorgeschichte aus der Kindheit lückenhaft ist.'),
  ('illicit-drug-use-counseling', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Screening auf Substanzkonsum, kombiniert mit Zugang zu wirksamer Behandlung, ermöglicht frühere Hilfe, wenn sie gebraucht wird.', 'Ein kurzes Gespräch über Substanzkonsum – in einem Rahmen mit echten Behandlungsmöglichkeiten – kann den Weg zu Unterstützung öffnen.'),
  ('physical-activity-counseling', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Regelmäßige Bewegung senkt das Herz-Kreislauf-Risiko und reduziert bei Erwachsenen ab 65 spürbar das Sturzrisiko.', 'Strebe mindestens 150 Minuten moderate Bewegung pro Woche an; sprich mit deiner Ärztin oder deinem Arzt über einen zu deinem Alltag passenden Plan.'),
  ('nutrition-counseling', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Eine ausgewogene Ernährung unterstützt die Herzgesundheit und hilft, gewichtsbezogene Risikofaktoren zu steuern.', 'Eine mediterrane Ernährungsweise ist ein sinnvoller Ausgangspunkt; frag deine Ärztin oder deinen Arzt nach einer auf deine Risikofaktoren abgestimmten Empfehlung.'),
  ('sexual-behavior-counseling', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Beratung zu sichereren Sexualpraktiken senkt das Risiko sexuell übertragbarer Infektionen.', 'Wenn du wechselnde Partner hast oder kürzlich eine Geschlechtskrankheit hattest, kann ein kurzes Gespräch über Schutzmaßnahmen (einschließlich Kondomen) dein Risiko künftig senken.'),
  ('sun-exposure-counseling', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Weniger UV-Exposition senkt das langfristige Hautkrebsrisiko, besonders bei hellem Hauttyp.', 'Vermeide Sonnenbrand, bevorzuge zwischen 11 und 15 Uhr den Schatten und verwende regelmäßig Sonnenschutz mit mindestens LSF 20.'),
  ('weight-bmi-screening', 'de', 'Alle 3 Jahre', 'Die Beobachtung des Gewichts über die Zeit hilft, Trends im Zusammenhang mit Herz-Kreislauf-Erkrankungen, Diabetes und anderen Erkrankungen frühzeitig zu erkennen.', 'Lass Gewicht und BMI im Rahmen der Routineversorgung alle 3 Jahre überprüfen.'),
  ('syphilis-screening', 'de', 'Wiederholung je nach fortbestehendem Risiko', 'Syphilis-Screening erkennt eine Infektion frühzeitig, wenn die Behandlung am einfachsten ist.', 'Wenn ein Syphilis-Risikofaktor bei dir vorliegt, lass dich testen und wiederhole den Test regelmäßig je nach fortbestehendem Risiko.'),
  ('chlamydia-gonorrhea-screening', 'de', 'Wiederholung je nach fortbestehendem Risiko', 'Beide Infektionen verlaufen oft ohne Symptome; Screening erkennt sie, bevor Komplikationen entstehen.', 'Frauen bis 24 werden routinemäßig getestet; danach richtet sich das Screening nach deinen Risikofaktoren.'),
  ('hepatitis-b-screening', 'de', 'Wiederholung je nach fortbestehendem Risiko', 'Hepatitis-B-Screening erkennt eine chronische Infektion, die sonst jahrelang unbemerkt bleiben kann.', 'Wenn du in einer Region mit höherer Hepatitis-B-Prävalenz geboren bist (oder enge Familie von dort hast) oder einen anderen Risikofaktor hast, lass dich testen.'),
  ('domestic-violence-screening', 'de', 'Fortlaufend, jährlich erneut geprüft', 'Häusliche Gewalt bleibt oft unerkannt; ein routinemäßiges Screening öffnet die Tür zu Unterstützung und Sicherheit.', 'Wenn sich etwas an deiner Beziehung unsicher anfühlt, kann dich deine Ärztin oder dein Arzt vertraulich mit Unterstützungsangeboten verbinden.')
on conflict (item_id, locale) do update set
  cadence_label = excluded.cadence_label,
  why_it_matters = excluded.why_it_matters,
  recommendation_text = excluded.recommendation_text,
  updated_at = now();
